# Create a data frame 
data <- data.frame(
  Week = c(26, 27, 28, 29, 30, 18, 19, 20, 21, 22),
  Sales = c(24864, 23809, 24476, 25279, 26263, 23688, 23922, 24421, 26197, 26765),
  TV = c(74.5, 74.5, 90.0, 90.0, 90.0, 160.0, 150.0, 0.0, 0.0, 180.0),
  Radio = c(66.5, 66.5, 75.0, 75.0, 75.0, 208.0, 208.0, 0.0, 0.0, 237.0),
  Fuel_Volume = c(61825, 62617, 60227, 63273, 65196, 65052, 63214, 63379, 63623, 62661),
  Fuel_Price = c(104.24, 103.97, 107.48, 111.75, 109.08, 130.95, 129.06, 129.28, 127.19, 129.19),
  Temp = c(27.9, 27.7, 29.1, 30.0, 29.3, 16.8, 17.3, 19.7, 21.1, 21.8),
  Prec = c(0.9, 1.3, 4.8, 3.1, 0.0, 12.7, 14.6, 5.9, 6.1, 7.3),
  Holiday = c(1, 1, 1, 1, 1, 1, 1, 0, 0, 0),
  Visits = c(7.0, 7.0, 5.9, 5.9, 5.9, 6.0, 6.0, 6.0, 6.0, 4.0)
)

# Display the first few rows of the data frame
head(data)

# Calculate the minimum, average, and maximum for Sales
sales_min <- min(data$Sales)
sales_avg <- mean(data$Sales)
sales_max <- max(data$Sales)

# Calculate the minimum, average, and maximum for Fuel Volume
fuel_vol_min <- min(data$Fuel_Volume)
fuel_vol_avg <- mean(data$Fuel_Volume)
fuel_vol_max <- max(data$Fuel_Volume)

# Calculate the minimum, average, and maximum for TV
tv_min <- min(data$TV)
tv_avg <- mean(data$TV)
tv_max <- max(data$TV)

# Calculate the minimum, average, and maximum for Radio
radio_min <- min(data$Radio)
radio_avg <- mean(data$Radio)
radio_max <- max(data$Radio)

# Create a summary data frame
summary_data <- data.frame(
  Variable = c("Sales", "Fuel Volume", "TV", "Radio"),
  Min = c(sales_min, fuel_vol_min, tv_min, radio_min),
  Average = c(sales_avg, fuel_vol_avg, tv_avg, radio_avg),
  Max = c(sales_max, fuel_vol_max, tv_max, radio_max)
)

# Print the summary
print(summary_data)


# 2. Assuming the data frame is named 'data' and has columns 'Sales' for c-store sales,
# 'TV' for TV GRPs, and 'Radio' for radio GRPs.

# Run the linear regression model
model <- lm(Sales ~ TV + Radio, data=data)

# Get a summary of the model to view the regression results
summary(model)

# 3. Add the temperature data to your data frame (assuming the name 'Temp')
data$Temp <- c(27.9, 27.7, 29.1, 30.0, 29.3, 16.8, 17.3, 19.7, 21.1, 21.8)

# Run the regression with the additional temperature variable
model_with_temp <- lm(Sales ~ TV + Radio + Temp, data=data)

# Get a summary of the model to view the regression results with temperature included
summary(model_with_temp)


# 3.3 Run the regression with only the temperature variable
model_temp_only <- lm(Sales ~ Temp, data=data)

# Get a summary of the model to view the regression results with only temperature
summary(model_temp_only)

# 4 Run the regression with all the variables
extended_model <- lm(Sales ~ TV + Radio + Fuel_Volume + Fuel_Price + Temp + Prec + Holiday + Visits, data=data)

# Get a summary of the model to view the regression results
summary(extended_model)

# Based on the summary, drop non-significant variables (this will vary based on your actual results)
# For example, if TV and Radio are not significant, you would drop them like so:
final_model <- lm(Sales ~ Fuel_Volume + Fuel_Price + Temp + Prec + Holiday + Visits, data=data)

# Get the summary of the final model
summary(final_model)

# 4.3 Given values from the regression output
beta_TV <- 3.670  # Coefficient for TV GRPs
SE_beta_TV <- 27.166  # Standard error for the TV GRPs coefficient
n <- 10  # Number of observations in the data

# Change in TV GRPs
delta_TV_GRPs <- 5

# Calculate the predicted increase in sales for 5 additional TV GRPs
predicted_increase <- beta_TV * delta_TV_GRPs

# Degrees of freedom for the t-distribution
df <- n - 2 - 1  # Subtracting 2 for the number of predictors and 1 for the intercept

# Critical t-value for a 95% confidence interval
t_critical <- qt(0.975, df)  # two-tailed

# Margin of error for the prediction
margin_of_error <- t_critical * SE_beta_TV * sqrt(delta_TV_GRPs)

# Lower and upper bounds of the 95% confidence interval
lower_bound <- predicted_increase - margin_of_error
upper_bound <- predicted_increase + margin_of_error

# Display the results
list(lower_bound = lower_bound, upper_bound = upper_bound, margin_of_error = margin_of_error)


# 4.4 Given values
beta_TV <- 3.670  # Coefficient for TV GRPs
cost_per_GRP <- 300  # Cost of a TV GRP in euros
margin_on_sales <- 0.30  # Weighted average margin on c-store sales
cost_price_per_unit <- 1  # Hypothetical cost price per unit
revenue_per_unit <- cost_price_per_unit * (1 + margin_on_sales)  # Revenue per unit of sales

# Calculate the additional sales generated by one TV GRP
additional_sales_per_GRP <- beta_TV * revenue_per_unit

# Calculate the additional profit from one TV GRP
additional_profit_per_GRP <- additional_sales_per_GRP * margin_on_sales

# Calculate the net impact of advertising per TV GRP
net_impact_per_GRP <- additional_profit_per_GRP - cost_per_GRP

# Display the results
list(additional_sales_per_GRP = additional_sales_per_GRP,
     additional_profit_per_GRP = additional_profit_per_GRP,
     net_impact_per_GRP = net_impact_per_GRP)

